// src/pages/_app.js
import 'tailwindcss/tailwind.css'
import '@/styles/globals.css';
import { Montserrat } from "next/font/google";
import Head from 'next/head';
import NavBar from '../components/NavBar';
import { Footer } from '../components/Footer';
import { AnimatePresence } from 'framer-motion';
import { useRouter } from 'next/router';

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont",  
//   weight: ["300", "400", "500", "600", "700"],
//   style: "normal",
//   display: "swap",
});

function MyApp({ Component, pageProps }) {
    const router = useRouter();
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={`${montserrat.variable} font-mont bg-light dark:bg-dark w-full min-h-screen`} >
                <NavBar/>
                <AnimatePresence mode='wait'>
                    <Component key={router.asPath} {...pageProps} />
                </AnimatePresence>
                <Footer />
            </main>
        </>        
    );
};

export default MyApp;
